name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install npm v10 globally
        run: npm install -g npm@latest

      - name: Set npm registry to public
        run: npm config set registry https://registry.npmjs.org/

      - name: Clean install environment
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Print npm debug log if exists
        run: cat /home/runner/.npm/_logs/*.log || echo "No npm log found"

      - name: Build site
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./dist
          production-deploy: true
          deploy-message: "GitHub Actions deploy from ${{ github.event.head_commit.message }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Handle Netlify deploy failure
        if: failure()
        run: |
          echo "Netlify deployment failed! Check the previous step's logs for details."
